'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class English
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("NHLGames.English", GetType(English).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Clear.
        '''</summary>
        Friend Shared ReadOnly Property btnClearConsole() As String
            Get
                Return ResourceManager.GetString("btnClearConsole", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Copy to Clipboard.
        '''</summary>
        Friend Shared ReadOnly Property btnCopyConsole() As String
            Get
                Return ResourceManager.GetString("btnCopyConsole", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to English.
        '''</summary>
        Friend Shared ReadOnly Property cbEnglish() As String
            Get
                Return ResourceManager.GetString("cbEnglish", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Français.
        '''</summary>
        Friend Shared ReadOnly Property cbFrench() As String
            Get
                Return ResourceManager.GetString("cbFrench", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Add the NHL.tv authentication bypass line to Hosts file.
        '''</summary>
        Friend Shared ReadOnly Property cbHostsAdd() As String
            Get
                Return ResourceManager.GetString("cbHostsAdd", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Copy to clipboard the authentication bypass line.
        '''</summary>
        Friend Shared ReadOnly Property cbHostsEntry() As String
            Get
                Return ResourceManager.GetString("cbHostsEntry", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Open Hosts file location.
        '''</summary>
        Friend Shared ReadOnly Property cbHostsLocation() As String
            Get
                Return ResourceManager.GetString("cbHostsLocation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Remove the NHL.tv authentication bypass line from Hosts file.
        '''</summary>
        Friend Shared ReadOnly Property cbHostsRemove() As String
            Get
                Return ResourceManager.GetString("cbHostsRemove", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Test if the NHL.tv authentication bypass works.
        '''</summary>
        Friend Shared ReadOnly Property cbHostsTest() As String
            Get
                Return ResourceManager.GetString("cbHostsTest", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to View Hosts file content in Notepad.
        '''</summary>
        Friend Shared ReadOnly Property cbHostsView() As String
            Get
                Return ResourceManager.GetString("cbHostsView", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to At the beginning of the stream.
        '''</summary>
        Friend Shared ReadOnly Property cbLiveReplayFeedStart() As String
            Get
                Return ResourceManager.GetString("cbLiveReplayFeedStart", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to When the event starts (game time).
        '''</summary>
        Friend Shared ReadOnly Property cbLiveReplayGameTime() As String
            Get
                Return ResourceManager.GetString("cbLiveReplayGameTime", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to When the game starts (drops the puck).
        '''</summary>
        Friend Shared ReadOnly Property cbLiveReplayPuckDrop() As String
            Get
                Return ResourceManager.GetString("cbLiveReplayPuckDrop", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Live - Today&apos;s games follow the live stream (Default).
        '''</summary>
        Friend Shared ReadOnly Property cbLiveStatusLive() As String
            Get
                Return ResourceManager.GetString("cbLiveStatusLive", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Replay - Today&apos;s games ignore live stream.
        '''</summary>
        Friend Shared ReadOnly Property cbLiveStatusReplay() As String
            Get
                Return ResourceManager.GetString("cbLiveStatusReplay", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Rewind - Today&apos;s games are set behind live stream.
        '''</summary>
        Friend Shared ReadOnly Property cbLiveStatusRewind() As String
            Get
                Return ResourceManager.GetString("cbLiveStatusRewind", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Good - 504p - 950Mb/hour.
        '''</summary>
        Friend Shared ReadOnly Property cbQualityGood() As String
            Get
                Return ResourceManager.GetString("cbQualityGood", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Great - 540p - 1.3Gb/hour.
        '''</summary>
        Friend Shared ReadOnly Property cbQualityGreat() As String
            Get
                Return ResourceManager.GetString("cbQualityGreat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Low - 288p - 500Mb/hour.
        '''</summary>
        Friend Shared ReadOnly Property cbQualityLow() As String
            Get
                Return ResourceManager.GetString("cbQualityLow", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mobile - 224p - 300Mb/hour.
        '''</summary>
        Friend Shared ReadOnly Property cbQualityMobile() As String
            Get
                Return ResourceManager.GetString("cbQualityMobile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Normal - 360p - 700Mb/hour.
        '''</summary>
        Friend Shared ReadOnly Property cbQualityNormal() As String
            Get
                Return ResourceManager.GetString("cbQualityNormal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Superb - 720p - 1.8Gb/hour.
        '''</summary>
        Friend Shared ReadOnly Property cbQualitySuperb() As String
            Get
                Return ResourceManager.GetString("cbQualitySuperb", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Excellent - 720p @ 60 fps - 2.5Gb/hour.
        '''</summary>
        Friend Shared ReadOnly Property cbQualitySuperb60fps() As String
            Get
                Return ResourceManager.GetString("cbQualitySuperb60fps", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Force Spotify to start.
        '''</summary>
        Friend Shared ReadOnly Property chkSpotifyForceToStart() As String
            Get
                Return ResourceManager.GetString("chkSpotifyForceToStart", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bind to Spotify.
        '''</summary>
        Friend Shared ReadOnly Property chkSpotifyHotkeys() As String
            Get
                Return ResourceManager.GetString("chkSpotifyHotkeys", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Always play next media.
        '''</summary>
        Friend Shared ReadOnly Property chkSpotifyPlayNextSong() As String
            Get
                Return ResourceManager.GetString("chkSpotifyPlayNextSong", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Undefined.
        '''</summary>
        Friend Shared ReadOnly Property enumGameState0() As String
            Get
                Return ResourceManager.GetString("enumGameState0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Scheduled.
        '''</summary>
        Friend Shared ReadOnly Property enumGameState1() As String
            Get
                Return ResourceManager.GetString("enumGameState1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cancelled.
        '''</summary>
        Friend Shared ReadOnly Property enumGameState10() As String
            Get
                Return ResourceManager.GetString("enumGameState10", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Delayed.
        '''</summary>
        Friend Shared ReadOnly Property enumGameState11() As String
            Get
                Return ResourceManager.GetString("enumGameState11", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pregame.
        '''</summary>
        Friend Shared ReadOnly Property enumGameState2() As String
            Get
                Return ResourceManager.GetString("enumGameState2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to In progress.
        '''</summary>
        Friend Shared ReadOnly Property enumGameState3() As String
            Get
                Return ResourceManager.GetString("enumGameState3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to In progress.
        '''</summary>
        Friend Shared ReadOnly Property enumGameState4() As String
            Get
                Return ResourceManager.GetString("enumGameState4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ended.
        '''</summary>
        Friend Shared ReadOnly Property enumGameState5() As String
            Get
                Return ResourceManager.GetString("enumGameState5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Final.
        '''</summary>
        Friend Shared ReadOnly Property enumGameState6() As String
            Get
                Return ResourceManager.GetString("enumGameState6", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Final.
        '''</summary>
        Friend Shared ReadOnly Property enumGameState7() As String
            Get
                Return ResourceManager.GetString("enumGameState7", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to TBD.
        '''</summary>
        Friend Shared ReadOnly Property enumGameState8() As String
            Get
                Return ResourceManager.GetString("enumGameState8", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Postponed.
        '''</summary>
        Friend Shared ReadOnly Property enumGameState9() As String
            Get
                Return ResourceManager.GetString("enumGameState9", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error: Checking access to path: {0}.
        '''</summary>
        Friend Shared ReadOnly Property errorAccessPath() As String
            Get
                Return ResourceManager.GetString("errorAccessPath", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [cli].
        '''</summary>
        Friend Shared ReadOnly Property errorCliStreamer() As String
            Get
                Return ResourceManager.GetString("errorCliStreamer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error : Failed to deserialize setting value of &apos;{0}&apos; to type &apos;{1}&apos;.
        '''</summary>
        Friend Shared ReadOnly Property errorDeserialize() As String
            Get
                Return ResourceManager.GetString("errorDeserialize", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to error:.
        '''</summary>
        Friend Shared ReadOnly Property errorDetection() As String
            Get
                Return ResourceManager.GetString("errorDetection", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to :.
        '''</summary>
        Friend Shared ReadOnly Property errorDoubleDot() As String
            Get
                Return ResourceManager.GetString("errorDoubleDot", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to exception.
        '''</summary>
        Friend Shared ReadOnly Property errorExceptionDetection() As String
            Get
                Return ResourceManager.GetString("errorExceptionDetection", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error: Failed to fetch games schedule..
        '''</summary>
        Friend Shared ReadOnly Property errorFetchingGames() As String
            Get
                Return ResourceManager.GetString("errorFetchingGames", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error: Code failed at: {0} - With exception: {1}.
        '''</summary>
        Friend Shared ReadOnly Property errorGeneral() As String
            Get
                Return ResourceManager.GetString("errorGeneral", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error: Selected Hostname is unreachable.
        '''</summary>
        Friend Shared ReadOnly Property errorHostname() As String
            Get
                Return ResourceManager.GetString("errorHostname", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error: Can&apos;t find mitmproxy : mitmproxy is a https proxy that we shipped with NHLGames. You probably moved it or deleted it. Please go to our GitHub page to get it back, NHLGames needs it.
        '''</summary>
        Friend Shared ReadOnly Property errorMitmProxyNotFound() As String
            Get
                Return ResourceManager.GetString("errorMitmProxyNotFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error: Can&apos;t find mpv.exe : mpv is a media player that we shipped with NHLGames. You probably moved it or deleted it. Please set a player, NHLGames needs one..
        '''</summary>
        Friend Shared ReadOnly Property errorMpvExe() As String
            Get
                Return ResourceManager.GetString("errorMpvExe", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error: No media player selected in settings..
        '''</summary>
        Friend Shared ReadOnly Property errorPlayerPathEmpty() As String
            Get
                Return ResourceManager.GetString("errorPlayerPathEmpty", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Warning: Failed to read app setting: {0}. Exception occured with: {1}.
        '''</summary>
        Friend Shared ReadOnly Property errorReadingSettings() As String
            Get
                Return ResourceManager.GetString("errorReadingSettings", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Warning: Can&apos;t set Ad Detection Modules. Verify if a Nugget package has a dependency of an older nugget package that you have installed: {0}.
        '''</summary>
        Friend Shared ReadOnly Property errorSetAdModule() As String
            Get
                Return ResourceManager.GetString("errorSetAdModule", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error:  Can&apos;t find the specified streamer. The streamer is used to send streams to your media player, please select the one that comes with NHLGames or select a valid path of Livestreamer.exe or Streamlink.exe.
        '''</summary>
        Friend Shared ReadOnly Property errorStreamerExe() As String
            Get
                Return ResourceManager.GetString("errorStreamerExe", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Warning: Starting stream failed. Try to use a different quality in settings, so it will try another stream..
        '''</summary>
        Friend Shared ReadOnly Property errorStreamFailedCantRead() As String
            Get
                Return ResourceManager.GetString("errorStreamFailedCantRead", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Game stream: Stream type unknown for the game {0} vs {1} : {2} - {3}.
        '''</summary>
        Friend Shared ReadOnly Property errorStreamTypeUnknown() As String
            Get
                Return ResourceManager.GetString("errorStreamTypeUnknown", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to unknown (server is not available).
        '''</summary>
        Friend Shared ReadOnly Property errorUnknownServerDown() As String
            Get
                Return ResourceManager.GetString("errorUnknownServerDown", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to warning:.
        '''</summary>
        Friend Shared ReadOnly Property errorWarning() As String
            Get
                Return ResourceManager.GetString("errorWarning", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Warning: Failed to write app settings. Make sure that NHLGames is inside a folder that your user account has full access, like a folder in your user workspace (Documents) or the root of your hard drive. Exception occured with: {0}.
        '''</summary>
        Friend Shared ReadOnly Property errorWritingSettings() As String
            Get
                Return ResourceManager.GetString("errorWritingSettings", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Intermission.
        '''</summary>
        Friend Shared ReadOnly Property gameIntermission() As String
            Get
                Return ResourceManager.GetString("gameIntermission", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 1st.
        '''</summary>
        Friend Shared ReadOnly Property gamePeriod1() As String
            Get
                Return ResourceManager.GetString("gamePeriod1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 2nd.
        '''</summary>
        Friend Shared ReadOnly Property gamePeriod2() As String
            Get
                Return ResourceManager.GetString("gamePeriod2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 3rd.
        '''</summary>
        Friend Shared ReadOnly Property gamePeriod3() As String
            Get
                Return ResourceManager.GetString("gamePeriod3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Final.
        '''</summary>
        Friend Shared ReadOnly Property gamePeriodFinal() As String
            Get
                Return ResourceManager.GetString("gamePeriodFinal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to OT.
        '''</summary>
        Friend Shared ReadOnly Property gamePeriodOt() As String
            Get
                Return ResourceManager.GetString("gamePeriodOt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0}OT.
        '''</summary>
        Friend Shared ReadOnly Property gamePeriodOtMore() As String
            Get
                Return ResourceManager.GetString("gamePeriodOtMore", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SO.
        '''</summary>
        Friend Shared ReadOnly Property gamePeriodSo() As String
            Get
                Return ResourceManager.GetString("gamePeriodSo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to leads.
        '''</summary>
        Friend Shared ReadOnly Property gameSeriesLead() As String
            Get
                Return ResourceManager.GetString("gameSeriesLead", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to tied.
        '''</summary>
        Friend Shared ReadOnly Property gameSeriesTied() As String
            Get
                Return ResourceManager.GetString("gameSeriesTied", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to wins.
        '''</summary>
        Friend Shared ReadOnly Property gameSeriesWin() As String
            Get
                Return ResourceManager.GetString("gameSeriesWin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to AWAY.
        '''</summary>
        Friend Shared ReadOnly Property grLblAWAY() As String
            Get
                Return ResourceManager.GetString("grLblAWAY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DIFF.
        '''</summary>
        Friend Shared ReadOnly Property grLblDIFF() As String
            Get
                Return ResourceManager.GetString("grLblDIFF", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to GA.
        '''</summary>
        Friend Shared ReadOnly Property grLblGA() As String
            Get
                Return ResourceManager.GetString("grLblGA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to GF.
        '''</summary>
        Friend Shared ReadOnly Property grLblGF() As String
            Get
                Return ResourceManager.GetString("grLblGF", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to GP.
        '''</summary>
        Friend Shared ReadOnly Property grLblGP() As String
            Get
                Return ResourceManager.GetString("grLblGP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to HOME.
        '''</summary>
        Friend Shared ReadOnly Property grLblHOME() As String
            Get
                Return ResourceManager.GetString("grLblHOME", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to L.
        '''</summary>
        Friend Shared ReadOnly Property grLblL() As String
            Get
                Return ResourceManager.GetString("grLblL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to L10.
        '''</summary>
        Friend Shared ReadOnly Property grLblL10() As String
            Get
                Return ResourceManager.GetString("grLblL10", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to OT.
        '''</summary>
        Friend Shared ReadOnly Property grLblOT() As String
            Get
                Return ResourceManager.GetString("grLblOT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to P%.
        '''</summary>
        Friend Shared ReadOnly Property grLblPerc() As String
            Get
                Return ResourceManager.GetString("grLblPerc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PTS.
        '''</summary>
        Friend Shared ReadOnly Property grLblPTS() As String
            Get
                Return ResourceManager.GetString("grLblPTS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ROW.
        '''</summary>
        Friend Shared ReadOnly Property grLblROW() As String
            Get
                Return ResourceManager.GetString("grLblROW", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to RW.
        '''</summary>
        Friend Shared ReadOnly Property grLblRW() As String
            Get
                Return ResourceManager.GetString("grLblRW", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to S/O.
        '''</summary>
        Friend Shared ReadOnly Property grLblShootOut() As String
            Get
                Return ResourceManager.GetString("grLblShootOut", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to STRK.
        '''</summary>
        Friend Shared ReadOnly Property grLblSTRK() As String
            Get
                Return ResourceManager.GetString("grLblSTRK", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to W.
        '''</summary>
        Friend Shared ReadOnly Property grLblW() As String
            Get
                Return ResourceManager.GetString("grLblW", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Use the alternate network.
        '''</summary>
        Friend Shared ReadOnly Property lblAlternateCdn() As String
            Get
                Return ResourceManager.GetString("lblAlternateCdn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Away Team : {0} {1}.
        '''</summary>
        Friend Shared ReadOnly Property lblAwayTeam() As String
            Get
                Return ResourceManager.GetString("lblAwayTeam", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0} camera views.
        '''</summary>
        Friend Shared ReadOnly Property lblCamViews() As String
            Get
                Return ResourceManager.GetString("lblCamViews", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Content Delivery Network.
        '''</summary>
        Friend Shared ReadOnly Property lblCdn() As String
            Get
                Return ResourceManager.GetString("lblCdn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Dark theme.
        '''</summary>
        Friend Shared ReadOnly Property lblDark() As String
            Get
                Return ResourceManager.GetString("lblDark", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0} endzone camera.
        '''</summary>
        Friend Shared ReadOnly Property lblEndzoneCam() As String
            Get
                Return ResourceManager.GetString("lblEndzoneCam", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0}, {1} {2}, {3}.
        '''</summary>
        Friend Shared ReadOnly Property lblFormatWeekMonthDayYear() As String
            Get
                Return ResourceManager.GetString("lblFormatWeekMonthDayYear", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to French Canadian stream.
        '''</summary>
        Friend Shared ReadOnly Property lblFrenchNetwork() As String
            Get
                Return ResourceManager.GetString("lblFrenchNetwork", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Game {0}.
        '''</summary>
        Friend Shared ReadOnly Property lblGame() As String
            Get
                Return ResourceManager.GetString("lblGame", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to GM {0}: {1}.
        '''</summary>
        Friend Shared ReadOnly Property lblGameAbv() As String
            Get
                Return ResourceManager.GetString("lblGameAbv", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Game Panel.
        '''</summary>
        Friend Shared ReadOnly Property lblGamePanel() As String
            Get
                Return ResourceManager.GetString("lblGamePanel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Home Team : {0} {1}.
        '''</summary>
        Friend Shared ReadOnly Property lblHomeTeam() As String
            Get
                Return ResourceManager.GetString("lblHomeTeam", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Server&apos;s Hostname.
        '''</summary>
        Friend Shared ReadOnly Property lblHostname() As String
            Get
                Return ResourceManager.GetString("lblHostname", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Language.
        '''</summary>
        Friend Shared ReadOnly Property lblLanguage() As String
            Get
                Return ResourceManager.GetString("lblLanguage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Live Replay.
        '''</summary>
        Friend Shared ReadOnly Property lblLiveReplay() As String
            Get
                Return ResourceManager.GetString("lblLiveReplay", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Live Rewind.
        '''</summary>
        Friend Shared ReadOnly Property lblLiveRewind() As String
            Get
                Return ResourceManager.GetString("lblLiveRewind", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0} minutes behind live stream ({1}).
        '''</summary>
        Friend Shared ReadOnly Property lblLiveRewindDetails() As String
            Get
                Return ResourceManager.GetString("lblLiveRewindDetails", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Media.
        '''</summary>
        Friend Shared ReadOnly Property lblMedia() As String
            Get
                Return ResourceManager.GetString("lblMedia", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Media control delay.
        '''</summary>
        Friend Shared ReadOnly Property lblMediaControlDelay() As String
            Get
                Return ResourceManager.GetString("lblMediaControlDelay", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Play/Pause the media player when an Ad is detected.
        '''</summary>
        Friend Shared ReadOnly Property lblMediaDesc() As String
            Get
                Return ResourceManager.GetString("lblMediaDesc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ad detection.
        '''</summary>
        Friend Shared ReadOnly Property lblModules() As String
            Get
                Return ResourceManager.GetString("lblModules", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Detects ads and notify activated apps below.
        '''</summary>
        Friend Shared ReadOnly Property lblModulesDesc() As String
            Get
                Return ResourceManager.GetString("lblModulesDesc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to MPC-HC Path.
        '''</summary>
        Friend Shared ReadOnly Property lblMpcPath() As String
            Get
                Return ResourceManager.GetString("lblMpcPath", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to MPV Path.
        '''</summary>
        Friend Shared ReadOnly Property lblMpvPath() As String
            Get
                Return ResourceManager.GetString("lblMpvPath", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to National stream.
        '''</summary>
        Friend Shared ReadOnly Property lblNationalNetwork() As String
            Get
                Return ResourceManager.GetString("lblNationalNetwork", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No game found.
        '''</summary>
        Friend Shared ReadOnly Property lblNoGames() As String
            Get
                Return ResourceManager.GetString("lblNoGames", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No stream available.
        '''</summary>
        Friend Shared ReadOnly Property lblNoStreamAvailable() As String
            Get
                Return ResourceManager.GetString("lblNoStreamAvailable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to OBS.
        '''</summary>
        Friend Shared ReadOnly Property lblObs() As String
            Get
                Return ResourceManager.GetString("lblObs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ad ending hotkey.
        '''</summary>
        Friend Shared ReadOnly Property lblObsAdEndingHotkey() As String
            Get
                Return ResourceManager.GetString("lblObsAdEndingHotkey", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ad starting hotkey.
        '''</summary>
        Friend Shared ReadOnly Property lblObsAdStartingHotkey() As String
            Get
                Return ResourceManager.GetString("lblObsAdStartingHotkey", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Switch scenes using binded keys when an Ad is detected.
        '''</summary>
        Friend Shared ReadOnly Property lblObsDesc() As String
            Get
                Return ResourceManager.GetString("lblObsDesc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  on {0}.
        '''</summary>
        Friend Shared ReadOnly Property lblOnNetwork() As String
            Get
                Return ResourceManager.GetString("lblOnNetwork", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Output.
        '''</summary>
        Friend Shared ReadOnly Property lblOutput() As String
            Get
                Return ResourceManager.GetString("lblOutput", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Default Player.
        '''</summary>
        Friend Shared ReadOnly Property lblPlayer() As String
            Get
                Return ResourceManager.GetString("lblPlayer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Players Args.
        '''</summary>
        Friend Shared ReadOnly Property lblPlayerArgs() As String
            Get
                Return ResourceManager.GetString("lblPlayerArgs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Preseason.
        '''</summary>
        Friend Shared ReadOnly Property lblPreseason() As String
            Get
                Return ResourceManager.GetString("lblPreseason", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Proxy Port.
        '''</summary>
        Friend Shared ReadOnly Property lblProxyPort() As String
            Get
                Return ResourceManager.GetString("lblProxyPort", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Stream Quality.
        '''</summary>
        Friend Shared ReadOnly Property lblQuality() As String
            Get
                Return ResourceManager.GetString("lblQuality", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Referee camera.
        '''</summary>
        Friend Shared ReadOnly Property lblRefCam() As String
            Get
                Return ResourceManager.GetString("lblRefCam", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Reset.
        '''</summary>
        Friend Shared ReadOnly Property lblReset() As String
            Get
                Return ResourceManager.GetString("lblReset", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Reset settings to default and restart.
        '''</summary>
        Friend Shared ReadOnly Property lblResetDesc() As String
            Get
                Return ResourceManager.GetString("lblResetDesc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Season.
        '''</summary>
        Friend Shared ReadOnly Property lblSeason() As String
            Get
                Return ResourceManager.GetString("lblSeason", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Server unavailable.
        '''</summary>
        Friend Shared ReadOnly Property lblServerDown() As String
            Get
                Return ResourceManager.GetString("lblServerDown", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Final scores.
        '''</summary>
        Friend Shared ReadOnly Property lblShowFinalScores() As String
            Get
                Return ResourceManager.GetString("lblShowFinalScores", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Live scores.
        '''</summary>
        Friend Shared ReadOnly Property lblShowLiveScores() As String
            Get
                Return ResourceManager.GetString("lblShowLiveScores", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Live remaining time.
        '''</summary>
        Friend Shared ReadOnly Property lblShowLiveTime() As String
            Get
                Return ResourceManager.GetString("lblShowLiveTime", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Series record.
        '''</summary>
        Friend Shared ReadOnly Property lblShowSeriesRecord() As String
            Get
                Return ResourceManager.GetString("lblShowSeriesRecord", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Standing rank.
        '''</summary>
        Friend Shared ReadOnly Property lblShowStanding() As String
            Get
                Return ResourceManager.GetString("lblShowStanding", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Teams city abbreviation.
        '''</summary>
        Friend Shared ReadOnly Property lblShowTeamCityAbr() As String
            Get
                Return ResourceManager.GetString("lblShowTeamCityAbr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Order by live games first.
        '''</summary>
        Friend Shared ReadOnly Property lblShowTodayLiveGamesFirst() As String
            Get
                Return ResourceManager.GetString("lblShowTodayLiveGamesFirst", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Streamer Path.
        '''</summary>
        Friend Shared ReadOnly Property lblSlPath() As String
            Get
                Return ResourceManager.GetString("lblSlPath", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Star camera.
        '''</summary>
        Friend Shared ReadOnly Property lblStarCam() As String
            Get
                Return ResourceManager.GetString("lblStarCam", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Streams available at game time.
        '''</summary>
        Friend Shared ReadOnly Property lblStreamAvailableAtGameTime() As String
            Get
                Return ResourceManager.GetString("lblStreamAvailableAtGameTime", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Streamer Args.
        '''</summary>
        Friend Shared ReadOnly Property lblStreamerArgs() As String
            Get
                Return ResourceManager.GetString("lblStreamerArgs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0} stream.
        '''</summary>
        Friend Shared ReadOnly Property lblTeamStream() As String
            Get
                Return ResourceManager.GetString("lblTeamStream", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to VLC Path.
        '''</summary>
        Friend Shared ReadOnly Property lblVlcPath() As String
            Get
                Return ResourceManager.GetString("lblVlcPath", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Today.
        '''</summary>
        Friend Shared ReadOnly Property lnkCalendarToday() As String
            Get
                Return ResourceManager.GetString("lnkCalendarToday", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to New version {0} is available! Click to update..
        '''</summary>
        Friend Shared ReadOnly Property lnkNewVersionText() As String
            Get
                Return ResourceManager.GetString("lnkNewVersionText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to /r/nhl_games.
        '''</summary>
        Friend Shared ReadOnly Property lnkSubreddit() As String
            Get
                Return ResourceManager.GetString("lnkSubreddit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Missing required Microsoft .NET 4.5 Framework!.
        '''</summary>
        Friend Shared ReadOnly Property missingFramework() As String
            Get
                Return ResourceManager.GetString("missingFramework", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Do you want to restart NHLGames to have the changes applied ?.
        '''</summary>
        Friend Shared ReadOnly Property msgAcceptToRestart() As String
            Get
                Return ResourceManager.GetString("msgAcceptToRestart", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Warning: Ad Detection: Unexpected Exception: {0}.
        '''</summary>
        Friend Shared ReadOnly Property msgAdDetectionException() As String
            Get
                Return ResourceManager.GetString("msgAdDetectionException", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Warning: Ad Detection: Problem initializing tasks: {0}.
        '''</summary>
        Friend Shared ReadOnly Property msgAdDetectionProbInit() As String
            Get
                Return ResourceManager.GetString("msgAdDetectionProbInit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Add our server to your hosts file.
        '''</summary>
        Friend Shared ReadOnly Property msgAddHost() As String
            Get
                Return ResourceManager.GetString("msgAddHost", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The {0} file is now set back to Read Only.
        '''</summary>
        Friend Shared ReadOnly Property msgAddReadOnly() As String
            Get
                Return ResourceManager.GetString("msgAddReadOnly", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Announcement!.
        '''</summary>
        Friend Shared ReadOnly Property msgAnnouncement() As String
            Get
                Return ResourceManager.GetString("msgAnnouncement", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Hosts: Backing up file: {0}.
        '''</summary>
        Friend Shared ReadOnly Property msgBackingHostsFile() As String
            Get
                Return ResourceManager.GetString("msgBackingHostsFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [CENSORED_STREAM_URL].
        '''</summary>
        Friend Shared ReadOnly Property msgCensoredStream() As String
            Get
                Return ResourceManager.GetString("msgCensoredStream", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Do you want to update to the latest version? Here the lastest changes:{0}{1}.
        '''</summary>
        Friend Shared ReadOnly Property msgChangeLog() As String
            Get
                Return ResourceManager.GetString("msgChangeLog", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Do you want to download the newest version?.
        '''</summary>
        Friend Shared ReadOnly Property msgChangeLogNone() As String
            Get
                Return ResourceManager.GetString("msgChangeLogNone", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Checking Requirements.
        '''</summary>
        Friend Shared ReadOnly Property msgChekingRequirements() As String
            Get
                Return ResourceManager.GetString("msgChekingRequirements", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Hosts: Removing existing entries from hosts file.
        '''</summary>
        Friend Shared ReadOnly Property msgCleanHostsFile() As String
            Get
                Return ResourceManager.GetString("msgCleanHostsFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [{0}] .
        '''</summary>
        Friend Shared ReadOnly Property msgDateTimeNow() As String
            Get
                Return ResourceManager.GetString("msgDateTimeNow", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to An error happened! {0}Click on [?] (top-right corner) to get to NHLGames documentation and search for your issue.{0}If not found, click on &quot;Copy to clipboard&quot; and paste it in a new thread on /r/nhl_games or open a new issue on our GitHub page. Make sure it was not already posted by someone else..
        '''</summary>
        Friend Shared ReadOnly Property msgErrorGeneralText() As String
            Get
                Return ResourceManager.GetString("msgErrorGeneralText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Failure.
        '''</summary>
        Friend Shared ReadOnly Property msgFailure() As String
            Get
                Return ResourceManager.GetString("msgFailure", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fetching.
        '''</summary>
        Friend Shared ReadOnly Property msgFetching() As String
            Get
                Return ResourceManager.GetString("msgFetching", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Games Found : {0}.
        '''</summary>
        Friend Shared ReadOnly Property msgGamesFound() As String
            Get
                Return ResourceManager.GetString("msgGamesFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0}: Game schedule for {1} from NHL.tv.
        '''</summary>
        Friend Shared ReadOnly Property msgGettingSchedule() As String
            Get
                Return ResourceManager.GetString("msgGettingSchedule", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Game stream: {0} not found or unavailable on the server.
        '''</summary>
        Friend Shared ReadOnly Property msgGettingStreamFailed() As String
            Get
                Return ResourceManager.GetString("msgGettingStreamFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to NHLGames needs to add a line to your Windows Hosts file so it can redirect NHL.tv streams properly. Do you let NHLGames add its hostname to this file?.
        '''</summary>
        Friend Shared ReadOnly Property msgHostnameSet() As String
            Get
                Return ResourceManager.GetString("msgHostnameSet", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The NHL.tv authentication bypass line &apos;&apos;{0}&apos;&apos; was copied to your clipboard. Use CTRL+V to paste it in your Hosts file..
        '''</summary>
        Friend Shared ReadOnly Property msgHostsCopyEntry() As String
            Get
                Return ResourceManager.GetString("msgHostsCopyEntry", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Hosts entry doesn&apos;t seem to be working :(.
        '''</summary>
        Friend Shared ReadOnly Property msgHostsFailure() As String
            Get
                Return ResourceManager.GetString("msgHostsFailure", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Windows Hosts file looks good: NHL.tv and NHLGames IP addresses matches :).
        '''</summary>
        Friend Shared ReadOnly Property msgHostsSuccess() As String
            Get
                Return ResourceManager.GetString("msgHostsSuccess", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Loading Games.
        '''</summary>
        Friend Shared ReadOnly Property msgLoadingGames() As String
            Get
                Return ResourceManager.GetString("msgLoadingGames", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to New Version {0} is available.
        '''</summary>
        Friend Shared ReadOnly Property msgNewVersionAvailable() As String
            Get
                Return ResourceManager.GetString("msgNewVersionAvailable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Make sure your antivirus did not delete a file or reinstall the app. Do you want to exit NHLGames?.
        '''</summary>
        Friend Shared ReadOnly Property msgNotStarting() As String
            Get
                Return ResourceManager.GetString("msgNotStarting", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ad.
        '''</summary>
        Friend Shared ReadOnly Property msgObsAdWord() As String
            Get
                Return ResourceManager.GetString("msgObsAdWord", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ad Detection: OBS is changing to {0} scene.
        '''</summary>
        Friend Shared ReadOnly Property msgObsChangingScene() As String
            Get
                Return ResourceManager.GetString("msgObsChangingScene", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Game.
        '''</summary>
        Friend Shared ReadOnly Property msgObsGameWord() As String
            Get
                Return ResourceManager.GetString("msgObsGameWord", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Warning: Ad Detection: OBS {0} scene hotkey not set.
        '''</summary>
        Friend Shared ReadOnly Property msgObsHotkeyNotSet() As String
            Get
                Return ResourceManager.GetString("msgObsHotkeyNotSet", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to OFF.
        '''</summary>
        Friend Shared ReadOnly Property msgOff() As String
            Get
                Return ResourceManager.GetString("msgOff", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ON.
        '''</summary>
        Friend Shared ReadOnly Property msgOn() As String
            Get
                Return ResourceManager.GetString("msgOn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Proxy is getting ready.
        '''</summary>
        Friend Shared ReadOnly Property msgProxyGettingReady() As String
            Get
                Return ResourceManager.GetString("msgProxyGettingReady", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to MLBAMProxy: Proxy is listening on local port {0}.
        '''</summary>
        Friend Shared ReadOnly Property msgProxyListening() As String
            Get
                Return ResourceManager.GetString("msgProxyListening", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to MLBAMProxy: Proxy {0} is getting ready.
        '''</summary>
        Friend Shared ReadOnly Property msgProxyStarting() As String
            Get
                Return ResourceManager.GetString("msgProxyStarting", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Status: The {0} file is no longer Read Only.
        '''</summary>
        Friend Shared ReadOnly Property msgRemoveReadOnly() As String
            Get
                Return ResourceManager.GetString("msgRemoveReadOnly", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Admin Access Required.
        '''</summary>
        Friend Shared ReadOnly Property msgRunAsAdmin() As String
            Get
                Return ResourceManager.GetString("msgRunAsAdmin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to NHLGames has detected a host entry which is no longer needed. Do you want to restart this application as an Administrator to remove the old entry?.
        '''</summary>
        Friend Shared ReadOnly Property msgRunAsAdminText() As String
            Get
                Return ResourceManager.GetString("msgRunAsAdminText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Status: Failed to download the game schedule file from {0}. Second attempt..
        '''</summary>
        Friend Shared ReadOnly Property msgServerNoRespondTryingAgain() As String
            Get
                Return ResourceManager.GetString("msgServerNoRespondTryingAgain", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Status: Server {0} seems down.
        '''</summary>
        Friend Shared ReadOnly Property msgServerSeemsDown() As String
            Get
                Return ResourceManager.GetString("msgServerSeemsDown", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Status: Setting updated for &apos;{0}&apos; to &apos;{1}&apos;.
        '''</summary>
        Friend Shared ReadOnly Property msgSettingUpdated() As String
            Get
                Return ResourceManager.GetString("msgSettingUpdated", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Warning: Ad Detection: Can&apos;t start Spotify: {0}.
        '''</summary>
        Friend Shared ReadOnly Property msgSpotifyCantStart() As String
            Get
                Return ResourceManager.GetString("msgSpotifyCantStart", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Warning: Ad Detection: Unexpected exception connecting to Spotify: {0}.
        '''</summary>
        Friend Shared ReadOnly Property msgSpotifyException() As String
            Get
                Return ResourceManager.GetString("msgSpotifyException", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Warning: Ad Detection: Spotify is not installed.
        '''</summary>
        Friend Shared ReadOnly Property msgSpotifyIsntInstalled() As String
            Get
                Return ResourceManager.GetString("msgSpotifyIsntInstalled", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ad Detection: Spotify didn&apos;t connect in time, try again..
        '''</summary>
        Friend Shared ReadOnly Property msgSpotifyNotConnected() As String
            Get
                Return ResourceManager.GetString("msgSpotifyNotConnected", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ad Detection: Spotify isn&apos;t running. Trying to start it....
        '''</summary>
        Friend Shared ReadOnly Property msgSpotifyNotRunning() As String
            Get
                Return ResourceManager.GetString("msgSpotifyNotRunning", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Starting: Streamer {0}.
        '''</summary>
        Friend Shared ReadOnly Property msgStartingStreamer() As String
            Get
                Return ResourceManager.GetString("msgStartingStreamer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Streamer:.
        '''</summary>
        Friend Shared ReadOnly Property msgStreamer() As String
            Get
                Return ResourceManager.GetString("msgStreamer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Streaming: {0} on {1} using {2} player.
        '''</summary>
        Friend Shared ReadOnly Property msgStreaming() As String
            Get
                Return ResourceManager.GetString("msgStreaming", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Success.
        '''</summary>
        Friend Shared ReadOnly Property msgSuccess() As String
            Get
                Return ResourceManager.GetString("msgSuccess", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0} vs {1}.
        '''</summary>
        Friend Shared ReadOnly Property msgTeamVsTeam() As String
            Get
                Return ResourceManager.GetString("msgTeamVsTeam", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0} enable.
        '''</summary>
        Friend Shared ReadOnly Property msgThisEnable() As String
            Get
                Return ResourceManager.GetString("msgThisEnable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [Value too large for display].
        '''</summary>
        Friend Shared ReadOnly Property msgValueTooLarge() As String
            Get
                Return ResourceManager.GetString("msgValueTooLarge", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Open Hosts File.
        '''</summary>
        Friend Shared ReadOnly Property msgViewHosts() As String
            Get
                Return ResourceManager.GetString("msgViewHosts", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Do you wish to view the changes NHLGames made to your Hosts file?.
        '''</summary>
        Friend Shared ReadOnly Property msgViewHostsText() As String
            Get
                Return ResourceManager.GetString("msgViewHostsText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Video On Demand Status: {0}.
        '''</summary>
        Friend Shared ReadOnly Property msgVOD() As String
            Get
                Return ResourceManager.GetString("msgVOD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No redirection server found!.
        '''</summary>
        Friend Shared ReadOnly Property noGameServer() As String
            Get
                Return ResourceManager.GetString("noGameServer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No Internet access!.
        '''</summary>
        Friend Shared ReadOnly Property noWebAccess() As String
            Get
                Return ResourceManager.GetString("noWebAccess", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Conference.
        '''</summary>
        Friend Shared ReadOnly Property tabConferenceStandings() As String
            Get
                Return ResourceManager.GetString("tabConferenceStandings", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Console.
        '''</summary>
        Friend Shared ReadOnly Property tabConsole() As String
            Get
                Return ResourceManager.GetString("tabConsole", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Division.
        '''</summary>
        Friend Shared ReadOnly Property tabDivisionStandings() As String
            Get
                Return ResourceManager.GetString("tabDivisionStandings", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Games.
        '''</summary>
        Friend Shared ReadOnly Property tabGames() As String
            Get
                Return ResourceManager.GetString("tabGames", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to League.
        '''</summary>
        Friend Shared ReadOnly Property tabLeagueStandings() As String
            Get
                Return ResourceManager.GetString("tabLeagueStandings", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Modules.
        '''</summary>
        Friend Shared ReadOnly Property tabModules() As String
            Get
                Return ResourceManager.GetString("tabModules", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Settings.
        '''</summary>
        Friend Shared ReadOnly Property tabSettings() As String
            Get
                Return ResourceManager.GetString("tabSettings", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Standings.
        '''</summary>
        Friend Shared ReadOnly Property tabStandings() As String
            Get
                Return ResourceManager.GetString("tabStandings", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Wild Card.
        '''</summary>
        Friend Shared ReadOnly Property tabWildCardStandings() As String
            Get
                Return ResourceManager.GetString("tabWildCardStandings", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Broken stream.
        '''</summary>
        Friend Shared ReadOnly Property tipBrokenStream() As String
            Get
                Return ResourceManager.GetString("tipBrokenStream", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Browse.
        '''</summary>
        Friend Shared ReadOnly Property tipBrowse() As String
            Get
                Return ResourceManager.GetString("tipBrowse", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Calendar.
        '''</summary>
        Friend Shared ReadOnly Property tipCalendar() As String
            Get
                Return ResourceManager.GetString("tipCalendar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Day before.
        '''</summary>
        Friend Shared ReadOnly Property tipDayLeft() As String
            Get
                Return ResourceManager.GetString("tipDayLeft", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Day after.
        '''</summary>
        Friend Shared ReadOnly Property tipDayRight() As String
            Get
                Return ResourceManager.GetString("tipDayRight", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Download MPC-HC.
        '''</summary>
        Friend Shared ReadOnly Property tipGetMpc() As String
            Get
                Return ResourceManager.GetString("tipGetMpc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Download VLC.
        '''</summary>
        Friend Shared ReadOnly Property tipGetVlc() As String
            Get
                Return ResourceManager.GetString("tipGetVlc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Documentation.
        '''</summary>
        Friend Shared ReadOnly Property tipHelp() As String
            Get
                Return ResourceManager.GetString("tipHelp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Execute action.
        '''</summary>
        Friend Shared ReadOnly Property tipHostsExecuteAction() As String
            Get
                Return ResourceManager.GetString("tipHostsExecuteAction", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Live.
        '''</summary>
        Friend Shared ReadOnly Property tipLiveStatusLive() As String
            Get
                Return ResourceManager.GetString("tipLiveStatusLive", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Replay.
        '''</summary>
        Friend Shared ReadOnly Property tipLiveStatusReplay() As String
            Get
                Return ResourceManager.GetString("tipLiveStatusReplay", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Rewind {0} min.
        '''</summary>
        Friend Shared ReadOnly Property tipLiveStatusRewind() As String
            Get
                Return ResourceManager.GetString("tipLiveStatusRewind", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Raising this value may fix music still playing after a commercial break..
        '''</summary>
        Friend Shared ReadOnly Property tipMediaControlDelay() As String
            Get
                Return ResourceManager.GetString("tipMediaControlDelay", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Rewind a live game by clicking once on the red Live icon at the top-left of a game panel.
        '''</summary>
        Friend Shared ReadOnly Property tipMessage1() As String
            Get
                Return ResourceManager.GetString("tipMessage1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cast a game to your Chromecast with the VLC 3.0 player menu: Playback &gt; Rendered &gt;Cast.
        '''</summary>
        Friend Shared ReadOnly Property tipMessage10() As String
            Get
                Return ResourceManager.GetString("tipMessage10", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Display the interface in black when enabling the Dark theme in settings.
        '''</summary>
        Friend Shared ReadOnly Property tipMessage2() As String
            Get
                Return ResourceManager.GetString("tipMessage2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Show scores, remaining period time and team names by customizing the game panel in settings.
        '''</summary>
        Friend Shared ReadOnly Property tipMessage3() As String
            Get
                Return ResourceManager.GetString("tipMessage3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Record any game on Windows 10 by enabling the Output option in settings.
        '''</summary>
        Friend Shared ReadOnly Property tipMessage4() As String
            Get
                Return ResourceManager.GetString("tipMessage4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Replay a live game by clicking twice on the red Live icon at the top-left of a game panel.
        '''</summary>
        Friend Shared ReadOnly Property tipMessage5() As String
            Get
                Return ResourceManager.GetString("tipMessage5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Find the documentation or an anwser to your issue on our Wiki. Click at the top-right on [?] to get there.
        '''</summary>
        Friend Shared ReadOnly Property tipMessage6() As String
            Get
                Return ResourceManager.GetString("tipMessage6", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Report any bug by opening an issue on Github. Click at the top-right on [?] to get there.
        '''</summary>
        Friend Shared ReadOnly Property tipMessage7() As String
            Get
                Return ResourceManager.GetString("tipMessage7", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Visit our subreddit /r/nhl_games to chat with other redditors about NHLGames.
        '''</summary>
        Friend Shared ReadOnly Property tipMessage8() As String
            Get
                Return ResourceManager.GetString("tipMessage8", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fast forward/rewind on a live game is only supported by the MPV player.
        '''</summary>
        Friend Shared ReadOnly Property tipMessage9() As String
            Get
                Return ResourceManager.GetString("tipMessage9", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Month before.
        '''</summary>
        Friend Shared ReadOnly Property tipMonthLeft() As String
            Get
                Return ResourceManager.GetString("tipMonthLeft", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Month after.
        '''</summary>
        Friend Shared ReadOnly Property tipMonthRight() As String
            Get
                Return ResourceManager.GetString("tipMonthRight", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Recap.
        '''</summary>
        Friend Shared ReadOnly Property tipRecap() As String
            Get
                Return ResourceManager.GetString("tipRecap", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Refresh.
        '''</summary>
        Friend Shared ReadOnly Property tipRefresh() As String
            Get
                Return ResourceManager.GetString("tipRefresh", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Keyboard shorcuts: (++)Page Up/Down(--) , (-)Arrow Left/Right(+).
        '''</summary>
        Friend Shared ReadOnly Property tipTrackBarMove() As String
            Get
                Return ResourceManager.GetString("tipTrackBarMove", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Year before.
        '''</summary>
        Friend Shared ReadOnly Property tipYearDown() As String
            Get
                Return ResourceManager.GetString("tipYearDown", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Year after.
        '''</summary>
        Friend Shared ReadOnly Property tipYearUp() As String
            Get
                Return ResourceManager.GetString("tipYearUp", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
