'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class French
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("NHLGames.French", GetType(French).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Effacer.
        '''</summary>
        Friend Shared ReadOnly Property btnClearConsole() As String
            Get
                Return ResourceManager.GetString("btnClearConsole", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Copier au presse-papier.
        '''</summary>
        Friend Shared ReadOnly Property btnCopyConsole() As String
            Get
                Return ResourceManager.GetString("btnCopyConsole", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to English.
        '''</summary>
        Friend Shared ReadOnly Property cbEnglish() As String
            Get
                Return ResourceManager.GetString("cbEnglish", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Français.
        '''</summary>
        Friend Shared ReadOnly Property cbFrench() As String
            Get
                Return ResourceManager.GetString("cbFrench", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ajouter la ligne de redirection de l&apos;authentifcation à NHL.tv au fichier Hosts.
        '''</summary>
        Friend Shared ReadOnly Property cbHostsAdd() As String
            Get
                Return ResourceManager.GetString("cbHostsAdd", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Copier dans le presse-papier la ligne de redirection.
        '''</summary>
        Friend Shared ReadOnly Property cbHostsEntry() As String
            Get
                Return ResourceManager.GetString("cbHostsEntry", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ouvrir l&apos;emplacement du fichier Hosts.
        '''</summary>
        Friend Shared ReadOnly Property cbHostsLocation() As String
            Get
                Return ResourceManager.GetString("cbHostsLocation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Retirer la ligne de redirection de l&apos;authentification à NHL.tv au fichier Hosts.
        '''</summary>
        Friend Shared ReadOnly Property cbHostsRemove() As String
            Get
                Return ResourceManager.GetString("cbHostsRemove", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tester si le contournement de l&apos;authentification à NHL.tv fonctionne.
        '''</summary>
        Friend Shared ReadOnly Property cbHostsTest() As String
            Get
                Return ResourceManager.GetString("cbHostsTest", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Voir le contenu du fichier Hosts dans bloc-notes.
        '''</summary>
        Friend Shared ReadOnly Property cbHostsView() As String
            Get
                Return ResourceManager.GetString("cbHostsView", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Au tout début du stream.
        '''</summary>
        Friend Shared ReadOnly Property cbLiveReplayFeedStart() As String
            Get
                Return ResourceManager.GetString("cbLiveReplayFeedStart", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Quand l&apos;évènement débute (heure du match).
        '''</summary>
        Friend Shared ReadOnly Property cbLiveReplayGameTime() As String
            Get
                Return ResourceManager.GetString("cbLiveReplayGameTime", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Quand le match commence (puck en jeu).
        '''</summary>
        Friend Shared ReadOnly Property cbLiveReplayPuckDrop() As String
            Get
                Return ResourceManager.GetString("cbLiveReplayPuckDrop", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to En direct - Les matchs du jour suivent le stream en direct (Default).
        '''</summary>
        Friend Shared ReadOnly Property cbLiveStatusLive() As String
            Get
                Return ResourceManager.GetString("cbLiveStatusLive", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Rejouer - Les matchs du jour ignorent le stream en direct.
        '''</summary>
        Friend Shared ReadOnly Property cbLiveStatusReplay() As String
            Get
                Return ResourceManager.GetString("cbLiveStatusReplay", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Reculer - Les matchs du jour sont positionnés derrière le stream en direct.
        '''</summary>
        Friend Shared ReadOnly Property cbLiveStatusRewind() As String
            Get
                Return ResourceManager.GetString("cbLiveStatusRewind", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bonne - 504p - 950Mb/heure.
        '''</summary>
        Friend Shared ReadOnly Property cbQualityGood() As String
            Get
                Return ResourceManager.GetString("cbQualityGood", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Géniale - 540p - 1.3Gb/heure.
        '''</summary>
        Friend Shared ReadOnly Property cbQualityGreat() As String
            Get
                Return ResourceManager.GetString("cbQualityGreat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Basse - 288p - 500Mb/heure.
        '''</summary>
        Friend Shared ReadOnly Property cbQualityLow() As String
            Get
                Return ResourceManager.GetString("cbQualityLow", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mobile - 224p - 300Mb/heure.
        '''</summary>
        Friend Shared ReadOnly Property cbQualityMobile() As String
            Get
                Return ResourceManager.GetString("cbQualityMobile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Moyenne - 360p - 700Mb/heure.
        '''</summary>
        Friend Shared ReadOnly Property cbQualityNormal() As String
            Get
                Return ResourceManager.GetString("cbQualityNormal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Superbe - 720p - 1.8Gb/heure.
        '''</summary>
        Friend Shared ReadOnly Property cbQualitySuperb() As String
            Get
                Return ResourceManager.GetString("cbQualitySuperb", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Excellente - 720p @ 60 fps - 2.5Gb/heure.
        '''</summary>
        Friend Shared ReadOnly Property cbQualitySuperb60fps() As String
            Get
                Return ResourceManager.GetString("cbQualitySuperb60fps", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Forcer le démarrage de Spotify.
        '''</summary>
        Friend Shared ReadOnly Property chkSpotifyForceToStart() As String
            Get
                Return ResourceManager.GetString("chkSpotifyForceToStart", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Se lier à Spotify.
        '''</summary>
        Friend Shared ReadOnly Property chkSpotifyHotkeys() As String
            Get
                Return ResourceManager.GetString("chkSpotifyHotkeys", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Toujours jouer le prochain média.
        '''</summary>
        Friend Shared ReadOnly Property chkSpotifyPlayNextSong() As String
            Get
                Return ResourceManager.GetString("chkSpotifyPlayNextSong", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Non défini.
        '''</summary>
        Friend Shared ReadOnly Property enumGameState0() As String
            Get
                Return ResourceManager.GetString("enumGameState0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to À venir.
        '''</summary>
        Friend Shared ReadOnly Property enumGameState1() As String
            Get
                Return ResourceManager.GetString("enumGameState1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Annulé.
        '''</summary>
        Friend Shared ReadOnly Property enumGameState10() As String
            Get
                Return ResourceManager.GetString("enumGameState10", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to En retard.
        '''</summary>
        Friend Shared ReadOnly Property enumGameState11() As String
            Get
                Return ResourceManager.GetString("enumGameState11", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Avant-match.
        '''</summary>
        Friend Shared ReadOnly Property enumGameState2() As String
            Get
                Return ResourceManager.GetString("enumGameState2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to En cours.
        '''</summary>
        Friend Shared ReadOnly Property enumGameState3() As String
            Get
                Return ResourceManager.GetString("enumGameState3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to En cours.
        '''</summary>
        Friend Shared ReadOnly Property enumGameState4() As String
            Get
                Return ResourceManager.GetString("enumGameState4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Terminé.
        '''</summary>
        Friend Shared ReadOnly Property enumGameState5() As String
            Get
                Return ResourceManager.GetString("enumGameState5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Final.
        '''</summary>
        Friend Shared ReadOnly Property enumGameState6() As String
            Get
                Return ResourceManager.GetString("enumGameState6", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Final.
        '''</summary>
        Friend Shared ReadOnly Property enumGameState7() As String
            Get
                Return ResourceManager.GetString("enumGameState7", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to À déterminer.
        '''</summary>
        Friend Shared ReadOnly Property enumGameState8() As String
            Get
                Return ResourceManager.GetString("enumGameState8", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Reporté.
        '''</summary>
        Friend Shared ReadOnly Property enumGameState9() As String
            Get
                Return ResourceManager.GetString("enumGameState9", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Entracte.
        '''</summary>
        Friend Shared ReadOnly Property gameIntermission() As String
            Get
                Return ResourceManager.GetString("gameIntermission", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 1ière.
        '''</summary>
        Friend Shared ReadOnly Property gamePeriod1() As String
            Get
                Return ResourceManager.GetString("gamePeriod1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 2ième.
        '''</summary>
        Friend Shared ReadOnly Property gamePeriod2() As String
            Get
                Return ResourceManager.GetString("gamePeriod2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 3ième.
        '''</summary>
        Friend Shared ReadOnly Property gamePeriod3() As String
            Get
                Return ResourceManager.GetString("gamePeriod3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Terminé.
        '''</summary>
        Friend Shared ReadOnly Property gamePeriodFinal() As String
            Get
                Return ResourceManager.GetString("gamePeriodFinal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to P.
        '''</summary>
        Friend Shared ReadOnly Property gamePeriodOt() As String
            Get
                Return ResourceManager.GetString("gamePeriodOt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0}E P.
        '''</summary>
        Friend Shared ReadOnly Property gamePeriodOtMore() As String
            Get
                Return ResourceManager.GetString("gamePeriodOtMore", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to FUS.
        '''</summary>
        Friend Shared ReadOnly Property gamePeriodSo() As String
            Get
                Return ResourceManager.GetString("gamePeriodSo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to mène.
        '''</summary>
        Friend Shared ReadOnly Property gameSeriesLead() As String
            Get
                Return ResourceManager.GetString("gameSeriesLead", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to égale.
        '''</summary>
        Friend Shared ReadOnly Property gameSeriesTied() As String
            Get
                Return ResourceManager.GetString("gameSeriesTied", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to gagne.
        '''</summary>
        Friend Shared ReadOnly Property gameSeriesWin() As String
            Get
                Return ResourceManager.GetString("gameSeriesWin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ÉTR.
        '''</summary>
        Friend Shared ReadOnly Property grLblAWAY() As String
            Get
                Return ResourceManager.GetString("grLblAWAY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DIFF.
        '''</summary>
        Friend Shared ReadOnly Property grLblDIFF() As String
            Get
                Return ResourceManager.GetString("grLblDIFF", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to BC.
        '''</summary>
        Friend Shared ReadOnly Property grLblGA() As String
            Get
                Return ResourceManager.GetString("grLblGA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to BP.
        '''</summary>
        Friend Shared ReadOnly Property grLblGF() As String
            Get
                Return ResourceManager.GetString("grLblGF", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to MJ.
        '''</summary>
        Friend Shared ReadOnly Property grLblGP() As String
            Get
                Return ResourceManager.GetString("grLblGP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DOM.
        '''</summary>
        Friend Shared ReadOnly Property grLblHOME() As String
            Get
                Return ResourceManager.GetString("grLblHOME", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to D.
        '''</summary>
        Friend Shared ReadOnly Property grLblL() As String
            Get
                Return ResourceManager.GetString("grLblL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 10D.
        '''</summary>
        Friend Shared ReadOnly Property grLblL10() As String
            Get
                Return ResourceManager.GetString("grLblL10", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DP.
        '''</summary>
        Friend Shared ReadOnly Property grLblOT() As String
            Get
                Return ResourceManager.GetString("grLblOT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to %PTS.
        '''</summary>
        Friend Shared ReadOnly Property grLblPerc() As String
            Get
                Return ResourceManager.GetString("grLblPerc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PTS.
        '''</summary>
        Friend Shared ReadOnly Property grLblPTS() As String
            Get
                Return ResourceManager.GetString("grLblPTS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to VRP.
        '''</summary>
        Friend Shared ReadOnly Property grLblROW() As String
            Get
                Return ResourceManager.GetString("grLblROW", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to VR.
        '''</summary>
        Friend Shared ReadOnly Property grLblRW() As String
            Get
                Return ResourceManager.GetString("grLblRW", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to TB.
        '''</summary>
        Friend Shared ReadOnly Property grLblShootOut() As String
            Get
                Return ResourceManager.GetString("grLblShootOut", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SÉQ.
        '''</summary>
        Friend Shared ReadOnly Property grLblSTRK() As String
            Get
                Return ResourceManager.GetString("grLblSTRK", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to V.
        '''</summary>
        Friend Shared ReadOnly Property grLblW() As String
            Get
                Return ResourceManager.GetString("grLblW", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Utiliser le réseau alternatif.
        '''</summary>
        Friend Shared ReadOnly Property lblAlternateCdn() As String
            Get
                Return ResourceManager.GetString("lblAlternateCdn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Visiteurs : {1} {0}.
        '''</summary>
        Friend Shared ReadOnly Property lblAwayTeam() As String
            Get
                Return ResourceManager.GetString("lblAwayTeam", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0} vues de caméra.
        '''</summary>
        Friend Shared ReadOnly Property lblCamViews() As String
            Get
                Return ResourceManager.GetString("lblCamViews", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Réseau de diffusion.
        '''</summary>
        Friend Shared ReadOnly Property lblCdn() As String
            Get
                Return ResourceManager.GetString("lblCdn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Thème sombre.
        '''</summary>
        Friend Shared ReadOnly Property lblDark() As String
            Get
                Return ResourceManager.GetString("lblDark", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Caméra zone {0}.
        '''</summary>
        Friend Shared ReadOnly Property lblEndzoneCam() As String
            Get
                Return ResourceManager.GetString("lblEndzoneCam", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0} {2} {1} {3}.
        '''</summary>
        Friend Shared ReadOnly Property lblFormatWeekMonthDayYear() As String
            Get
                Return ResourceManager.GetString("lblFormatWeekMonthDayYear", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Stream canadien français.
        '''</summary>
        Friend Shared ReadOnly Property lblFrenchNetwork() As String
            Get
                Return ResourceManager.GetString("lblFrenchNetwork", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Match {0}.
        '''</summary>
        Friend Shared ReadOnly Property lblGame() As String
            Get
                Return ResourceManager.GetString("lblGame", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to M{0}: {1}.
        '''</summary>
        Friend Shared ReadOnly Property lblGameAbv() As String
            Get
                Return ResourceManager.GetString("lblGameAbv", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Panneau de partie.
        '''</summary>
        Friend Shared ReadOnly Property lblGamePanel() As String
            Get
                Return ResourceManager.GetString("lblGamePanel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Locaux : {1} {0}.
        '''</summary>
        Friend Shared ReadOnly Property lblHomeTeam() As String
            Get
                Return ResourceManager.GetString("lblHomeTeam", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nom de domaine.
        '''</summary>
        Friend Shared ReadOnly Property lblHostname() As String
            Get
                Return ResourceManager.GetString("lblHostname", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Langue.
        '''</summary>
        Friend Shared ReadOnly Property lblLanguage() As String
            Get
                Return ResourceManager.GetString("lblLanguage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Rejoue en direct.
        '''</summary>
        Friend Shared ReadOnly Property lblLiveReplay() As String
            Get
                Return ResourceManager.GetString("lblLiveReplay", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Reculer en direct.
        '''</summary>
        Friend Shared ReadOnly Property lblLiveRewind() As String
            Get
                Return ResourceManager.GetString("lblLiveRewind", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0} minutes derrière le stream en direct ({1}).
        '''</summary>
        Friend Shared ReadOnly Property lblLiveRewindDetails() As String
            Get
                Return ResourceManager.GetString("lblLiveRewindDetails", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Média.
        '''</summary>
        Friend Shared ReadOnly Property lblMedia() As String
            Get
                Return ResourceManager.GetString("lblMedia", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Délai des contrôles de médias.
        '''</summary>
        Friend Shared ReadOnly Property lblMediaControlDelay() As String
            Get
                Return ResourceManager.GetString("lblMediaControlDelay", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Joue/Pause le lecteur média quand une annonce est détectée.
        '''</summary>
        Friend Shared ReadOnly Property lblMediaDesc() As String
            Get
                Return ResourceManager.GetString("lblMediaDesc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Détection de publicité.
        '''</summary>
        Friend Shared ReadOnly Property lblModules() As String
            Get
                Return ResourceManager.GetString("lblModules", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Détecte les annonces et informe les applications activées ci-dessous.
        '''</summary>
        Friend Shared ReadOnly Property lblModulesDesc() As String
            Get
                Return ResourceManager.GetString("lblModulesDesc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Emplacement MPC-HC.
        '''</summary>
        Friend Shared ReadOnly Property lblMpcPath() As String
            Get
                Return ResourceManager.GetString("lblMpcPath", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Emplacement MPV.
        '''</summary>
        Friend Shared ReadOnly Property lblMpvPath() As String
            Get
                Return ResourceManager.GetString("lblMpvPath", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Stream national.
        '''</summary>
        Friend Shared ReadOnly Property lblNationalNetwork() As String
            Get
                Return ResourceManager.GetString("lblNationalNetwork", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Aucun match trouvé.
        '''</summary>
        Friend Shared ReadOnly Property lblNoGames() As String
            Get
                Return ResourceManager.GetString("lblNoGames", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Streams indisponible.
        '''</summary>
        Friend Shared ReadOnly Property lblNoStreamAvailable() As String
            Get
                Return ResourceManager.GetString("lblNoStreamAvailable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to OBS.
        '''</summary>
        Friend Shared ReadOnly Property lblObs() As String
            Get
                Return ResourceManager.GetString("lblObs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Raccourci clavier: Fin d&apos;annonce.
        '''</summary>
        Friend Shared ReadOnly Property lblObsAdEndingHotkey() As String
            Get
                Return ResourceManager.GetString("lblObsAdEndingHotkey", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Raccourci clavier: Début d&apos;annonce.
        '''</summary>
        Friend Shared ReadOnly Property lblObsAdStartingHotkey() As String
            Get
                Return ResourceManager.GetString("lblObsAdStartingHotkey", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Change de fenêtre selon les touches configurées quand une annonce est détectée.
        '''</summary>
        Friend Shared ReadOnly Property lblObsDesc() As String
            Get
                Return ResourceManager.GetString("lblObsDesc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  sur {0}.
        '''</summary>
        Friend Shared ReadOnly Property lblOnNetwork() As String
            Get
                Return ResourceManager.GetString("lblOnNetwork", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sauvegarde.
        '''</summary>
        Friend Shared ReadOnly Property lblOutput() As String
            Get
                Return ResourceManager.GetString("lblOutput", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Lecteur par défaut.
        '''</summary>
        Friend Shared ReadOnly Property lblPlayer() As String
            Get
                Return ResourceManager.GetString("lblPlayer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Lecteur args. supp..
        '''</summary>
        Friend Shared ReadOnly Property lblPlayerArgs() As String
            Get
                Return ResourceManager.GetString("lblPlayerArgs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Présaison.
        '''</summary>
        Friend Shared ReadOnly Property lblPreseason() As String
            Get
                Return ResourceManager.GetString("lblPreseason", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Port proxy.
        '''</summary>
        Friend Shared ReadOnly Property lblProxyPort() As String
            Get
                Return ResourceManager.GetString("lblProxyPort", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Qualité vidéo.
        '''</summary>
        Friend Shared ReadOnly Property lblQuality() As String
            Get
                Return ResourceManager.GetString("lblQuality", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Caméra de l&apos;arbitre.
        '''</summary>
        Friend Shared ReadOnly Property lblRefCam() As String
            Get
                Return ResourceManager.GetString("lblRefCam", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Réinitialiser.
        '''</summary>
        Friend Shared ReadOnly Property lblReset() As String
            Get
                Return ResourceManager.GetString("lblReset", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Réinitialiser aux paramètres par défaut et rédémarrer.
        '''</summary>
        Friend Shared ReadOnly Property lblResetDesc() As String
            Get
                Return ResourceManager.GetString("lblResetDesc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Saison.
        '''</summary>
        Friend Shared ReadOnly Property lblSeason() As String
            Get
                Return ResourceManager.GetString("lblSeason", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Serveur indisponible.
        '''</summary>
        Friend Shared ReadOnly Property lblServerDown() As String
            Get
                Return ResourceManager.GetString("lblServerDown", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Résultats finaux.
        '''</summary>
        Friend Shared ReadOnly Property lblShowFinalScores() As String
            Get
                Return ResourceManager.GetString("lblShowFinalScores", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Résultats en direct.
        '''</summary>
        Friend Shared ReadOnly Property lblShowLiveScores() As String
            Get
                Return ResourceManager.GetString("lblShowLiveScores", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Temps restant en direct.
        '''</summary>
        Friend Shared ReadOnly Property lblShowLiveTime() As String
            Get
                Return ResourceManager.GetString("lblShowLiveTime", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Détails des séries.
        '''</summary>
        Friend Shared ReadOnly Property lblShowSeriesRecord() As String
            Get
                Return ResourceManager.GetString("lblShowSeriesRecord", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Rang de classement.
        '''</summary>
        Friend Shared ReadOnly Property lblShowStanding() As String
            Get
                Return ResourceManager.GetString("lblShowStanding", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Abbréviation de la ville des équipes.
        '''</summary>
        Friend Shared ReadOnly Property lblShowTeamCityAbr() As String
            Get
                Return ResourceManager.GetString("lblShowTeamCityAbr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Classer les parties en direct en premier.
        '''</summary>
        Friend Shared ReadOnly Property lblShowTodayLiveGamesFirst() As String
            Get
                Return ResourceManager.GetString("lblShowTodayLiveGamesFirst", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Emplacement du Streamer.
        '''</summary>
        Friend Shared ReadOnly Property lblSlPath() As String
            Get
                Return ResourceManager.GetString("lblSlPath", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Caméra du joueur.
        '''</summary>
        Friend Shared ReadOnly Property lblStarCam() As String
            Get
                Return ResourceManager.GetString("lblStarCam", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Streams disponible à l&apos;heure du match.
        '''</summary>
        Friend Shared ReadOnly Property lblStreamAvailableAtGameTime() As String
            Get
                Return ResourceManager.GetString("lblStreamAvailableAtGameTime", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Streamer args. supp..
        '''</summary>
        Friend Shared ReadOnly Property lblStreamerArgs() As String
            Get
                Return ResourceManager.GetString("lblStreamerArgs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0} stream.
        '''</summary>
        Friend Shared ReadOnly Property lblTeamStream() As String
            Get
                Return ResourceManager.GetString("lblTeamStream", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Emplacement VLC.
        '''</summary>
        Friend Shared ReadOnly Property lblVlcPath() As String
            Get
                Return ResourceManager.GetString("lblVlcPath", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Aujourd&apos;hui.
        '''</summary>
        Friend Shared ReadOnly Property lnkCalendarToday() As String
            Get
                Return ResourceManager.GetString("lnkCalendarToday", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nouvelle version {0} est disponible! Cliquer pour mettre à jour..
        '''</summary>
        Friend Shared ReadOnly Property lnkNewVersionText() As String
            Get
                Return ResourceManager.GetString("lnkNewVersionText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Microsoft .NET 4.5 Framework requis manquant!.
        '''</summary>
        Friend Shared ReadOnly Property missingFramework() As String
            Get
                Return ResourceManager.GetString("missingFramework", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Voulez-vous redémarrer NHLGames pour appliquer les changements?.
        '''</summary>
        Friend Shared ReadOnly Property msgAcceptToRestart() As String
            Get
                Return ResourceManager.GetString("msgAcceptToRestart", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ajouter l&apos;entrée du serveur au fichier Hosts.
        '''</summary>
        Friend Shared ReadOnly Property msgAddHost() As String
            Get
                Return ResourceManager.GetString("msgAddHost", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Annonce!.
        '''</summary>
        Friend Shared ReadOnly Property msgAnnouncement() As String
            Get
                Return ResourceManager.GetString("msgAnnouncement", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Voulez-vous mettre à jour à la dernière version? Voici les derniers changements:{0}{1}.
        '''</summary>
        Friend Shared ReadOnly Property msgChangeLog() As String
            Get
                Return ResourceManager.GetString("msgChangeLog", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Voulez-vous télécharger la nouvelle version?.
        '''</summary>
        Friend Shared ReadOnly Property msgChangeLogNone() As String
            Get
                Return ResourceManager.GetString("msgChangeLogNone", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Validation des exigences.
        '''</summary>
        Friend Shared ReadOnly Property msgChekingRequirements() As String
            Get
                Return ResourceManager.GetString("msgChekingRequirements", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Une erreur est survenue!{0}Cliquez sur [?] (coin supérieur droit) pour voir la documentation en anglais de NHLGames et rechercher votre problème{0}Si introuvable, cliquez sur &quot;Copier au presse-papier&quot; et collez dans un nouveau sujet sur /r/nhl_games ou ouvrez un &quot;issue&quot; sur notre page GitHub. Soyez certain qu&apos;aucun sujet (thread) n&apos;y réfère déjà..
        '''</summary>
        Friend Shared ReadOnly Property msgErrorGeneralText() As String
            Get
                Return ResourceManager.GetString("msgErrorGeneralText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Erreur.
        '''</summary>
        Friend Shared ReadOnly Property msgFailure() As String
            Get
                Return ResourceManager.GetString("msgFailure", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Matchs trouvés : {0}.
        '''</summary>
        Friend Shared ReadOnly Property msgGamesFound() As String
            Get
                Return ResourceManager.GetString("msgGamesFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to NHLGames doit ajouter une ligne à votre fichier Hosts de Windows pour qu&apos;il puisse rediriger efficacement les streams de NHL.tv. Laissez-vous NHLGames ajouter son domaine à ce fichier?.
        '''</summary>
        Friend Shared ReadOnly Property msgHostnameSet() As String
            Get
                Return ResourceManager.GetString("msgHostnameSet", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to La ligne de redirection de l&apos;authentifcation à NHL.tv &apos;&apos;{0}&apos;&apos; a été copiée dans votre presse-papier. Utiliser CTRL+V pour la coller dans le fichier Hosts..
        '''</summary>
        Friend Shared ReadOnly Property msgHostsCopyEntry() As String
            Get
                Return ResourceManager.GetString("msgHostsCopyEntry", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to L&apos;entrée dans le fichier Hosts ne semble pas fonctionner :(.
        '''</summary>
        Friend Shared ReadOnly Property msgHostsFailure() As String
            Get
                Return ResourceManager.GetString("msgHostsFailure", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Le fichier Hosts de Windows semble fonctionnel: Les adresses IP de NHL.tv et NHLGames correspondent  :).
        '''</summary>
        Friend Shared ReadOnly Property msgHostsSuccess() As String
            Get
                Return ResourceManager.GetString("msgHostsSuccess", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chargement des matchs.
        '''</summary>
        Friend Shared ReadOnly Property msgLoadingGames() As String
            Get
                Return ResourceManager.GetString("msgLoadingGames", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nouvelle version {0} disponible.
        '''</summary>
        Friend Shared ReadOnly Property msgNewVersionAvailable() As String
            Get
                Return ResourceManager.GetString("msgNewVersionAvailable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Assurez-vous que votre antivirus n&apos;est pas effacé un fichier, sinon réinstallez l&apos;app. Voulez-vous quitter NHLGames?.
        '''</summary>
        Friend Shared ReadOnly Property msgNotStarting() As String
            Get
                Return ResourceManager.GetString("msgNotStarting", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Le proxy démarre.
        '''</summary>
        Friend Shared ReadOnly Property msgProxyGettingReady() As String
            Get
                Return ResourceManager.GetString("msgProxyGettingReady", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Accès d&apos;administrateur requis.
        '''</summary>
        Friend Shared ReadOnly Property msgRunAsAdmin() As String
            Get
                Return ResourceManager.GetString("msgRunAsAdmin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to NHLGames a détecté une entrée au fichier Hosts qui n&apos;est plus nécessaire.  Voulez-vous qu&apos;elle redémarre avec le droit d&apos;administrateur pour supprimer l&apos;ancienne entrée?.
        '''</summary>
        Friend Shared ReadOnly Property msgRunAsAdminText() As String
            Get
                Return ResourceManager.GetString("msgRunAsAdminText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Succès.
        '''</summary>
        Friend Shared ReadOnly Property msgSuccess() As String
            Get
                Return ResourceManager.GetString("msgSuccess", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0} vs {1}.
        '''</summary>
        Friend Shared ReadOnly Property msgTeamVsTeam() As String
            Get
                Return ResourceManager.GetString("msgTeamVsTeam", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Voir le fichier Hosts.
        '''</summary>
        Friend Shared ReadOnly Property msgViewHosts() As String
            Get
                Return ResourceManager.GetString("msgViewHosts", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Voulez-vous voir les changements apportés au fichier Hosts?.
        '''</summary>
        Friend Shared ReadOnly Property msgViewHostsText() As String
            Get
                Return ResourceManager.GetString("msgViewHostsText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Aucun serveur de redirection trouvé!.
        '''</summary>
        Friend Shared ReadOnly Property noGameServer() As String
            Get
                Return ResourceManager.GetString("noGameServer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Aucun accès à Internet!.
        '''</summary>
        Friend Shared ReadOnly Property noWebAccess() As String
            Get
                Return ResourceManager.GetString("noWebAccess", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Association.
        '''</summary>
        Friend Shared ReadOnly Property tabConferenceStandings() As String
            Get
                Return ResourceManager.GetString("tabConferenceStandings", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Console.
        '''</summary>
        Friend Shared ReadOnly Property tabConsole() As String
            Get
                Return ResourceManager.GetString("tabConsole", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Division.
        '''</summary>
        Friend Shared ReadOnly Property tabDivisionStandings() As String
            Get
                Return ResourceManager.GetString("tabDivisionStandings", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Matchs.
        '''</summary>
        Friend Shared ReadOnly Property tabGames() As String
            Get
                Return ResourceManager.GetString("tabGames", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ligue.
        '''</summary>
        Friend Shared ReadOnly Property tabLeagueStandings() As String
            Get
                Return ResourceManager.GetString("tabLeagueStandings", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Modules.
        '''</summary>
        Friend Shared ReadOnly Property tabModules() As String
            Get
                Return ResourceManager.GetString("tabModules", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Paramètres.
        '''</summary>
        Friend Shared ReadOnly Property tabSettings() As String
            Get
                Return ResourceManager.GetString("tabSettings", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Classements.
        '''</summary>
        Friend Shared ReadOnly Property tabStandings() As String
            Get
                Return ResourceManager.GetString("tabStandings", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Quatrième As.
        '''</summary>
        Friend Shared ReadOnly Property tabWildCardStandings() As String
            Get
                Return ResourceManager.GetString("tabWildCardStandings", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Stream brisé.
        '''</summary>
        Friend Shared ReadOnly Property tipBrokenStream() As String
            Get
                Return ResourceManager.GetString("tipBrokenStream", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Parcourir.
        '''</summary>
        Friend Shared ReadOnly Property tipBrowse() As String
            Get
                Return ResourceManager.GetString("tipBrowse", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Calendrier.
        '''</summary>
        Friend Shared ReadOnly Property tipCalendar() As String
            Get
                Return ResourceManager.GetString("tipCalendar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Jour précédent.
        '''</summary>
        Friend Shared ReadOnly Property tipDayLeft() As String
            Get
                Return ResourceManager.GetString("tipDayLeft", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Jour suivant.
        '''</summary>
        Friend Shared ReadOnly Property tipDayRight() As String
            Get
                Return ResourceManager.GetString("tipDayRight", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Download MPC-HC.
        '''</summary>
        Friend Shared ReadOnly Property tipGetMpc() As String
            Get
                Return ResourceManager.GetString("tipGetMpc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Download VLC.
        '''</summary>
        Friend Shared ReadOnly Property tipGetVlc() As String
            Get
                Return ResourceManager.GetString("tipGetVlc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Documentation.
        '''</summary>
        Friend Shared ReadOnly Property tipHelp() As String
            Get
                Return ResourceManager.GetString("tipHelp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Exécuter l&apos;action.
        '''</summary>
        Friend Shared ReadOnly Property tipHostsExecuteAction() As String
            Get
                Return ResourceManager.GetString("tipHostsExecuteAction", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to En direct.
        '''</summary>
        Friend Shared ReadOnly Property tipLiveStatusLive() As String
            Get
                Return ResourceManager.GetString("tipLiveStatusLive", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Rejouer.
        '''</summary>
        Friend Shared ReadOnly Property tipLiveStatusReplay() As String
            Get
                Return ResourceManager.GetString("tipLiveStatusReplay", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Reculer de {0} min.
        '''</summary>
        Friend Shared ReadOnly Property tipLiveStatusRewind() As String
            Get
                Return ResourceManager.GetString("tipLiveStatusRewind", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Augmenter cette valeur peut corriger les médias qui continue après une pause commerciale..
        '''</summary>
        Friend Shared ReadOnly Property tipMediaControlDelay() As String
            Get
                Return ResourceManager.GetString("tipMediaControlDelay", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Reculer un match en direct: En appuyant une fois sur l&apos;icone Live au haut-gauche d&apos;un panneau de match.
        '''</summary>
        Friend Shared ReadOnly Property tipMessage1() As String
            Get
                Return ResourceManager.GetString("tipMessage1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Castez un match à votre Chromecast avec le menu du lecteur VLC 3.0: Playback &gt; Rendered &gt;Cast.
        '''</summary>
        Friend Shared ReadOnly Property tipMessage10() As String
            Get
                Return ResourceManager.GetString("tipMessage10", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Afficher l&apos;interface en noir en activant le thème Sombre dans les paramètres.
        '''</summary>
        Friend Shared ReadOnly Property tipMessage2() As String
            Get
                Return ResourceManager.GetString("tipMessage2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Afficher le pointage, temps de période restant et le nom des équipes en personnalissant le panneau de match dans les paramètres.
        '''</summary>
        Friend Shared ReadOnly Property tipMessage3() As String
            Get
                Return ResourceManager.GetString("tipMessage3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Enregistrer n&apos;importe quel match sur Windows 10 en activant l&apos;option de sauvegarde dans les paramètres.
        '''</summary>
        Friend Shared ReadOnly Property tipMessage4() As String
            Get
                Return ResourceManager.GetString("tipMessage4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Rejouer un match en direct: En appuyant deux fois sur l&apos;icone Live au haut-gauche d&apos;un panneau de match.
        '''</summary>
        Friend Shared ReadOnly Property tipMessage5() As String
            Get
                Return ResourceManager.GetString("tipMessage5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Trouvez la documentation ou réponse à un problème sur notre Wiki. Cliquez en haut-droite sur [?] pour y accéder.
        '''</summary>
        Friend Shared ReadOnly Property tipMessage6() As String
            Get
                Return ResourceManager.GetString("tipMessage6", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Rapporter tout problème en ouvrant un issue sur GitHub. Cliquez en haut-droit sur [?] pour y accéder.
        '''</summary>
        Friend Shared ReadOnly Property tipMessage7() As String
            Get
                Return ResourceManager.GetString("tipMessage7", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Visitez notre subreddit /r/nhl_games pour discuter avec d&apos;autres redditeurs de NHLGames.
        '''</summary>
        Friend Shared ReadOnly Property tipMessage8() As String
            Get
                Return ResourceManager.GetString("tipMessage8", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to L&apos;avance/recule rapide d&apos;un match en direct est seulement supporté par le lecteur MPV.
        '''</summary>
        Friend Shared ReadOnly Property tipMessage9() As String
            Get
                Return ResourceManager.GetString("tipMessage9", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mois précédent.
        '''</summary>
        Friend Shared ReadOnly Property tipMonthLeft() As String
            Get
                Return ResourceManager.GetString("tipMonthLeft", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mois suivant.
        '''</summary>
        Friend Shared ReadOnly Property tipMonthRight() As String
            Get
                Return ResourceManager.GetString("tipMonthRight", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Résumé.
        '''</summary>
        Friend Shared ReadOnly Property tipRecap() As String
            Get
                Return ResourceManager.GetString("tipRecap", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Rafraîchir.
        '''</summary>
        Friend Shared ReadOnly Property tipRefresh() As String
            Get
                Return ResourceManager.GetString("tipRefresh", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Raccourcis claviers: (++)Page Haut/Bas(--) , (-)Gauche/Droite(+).
        '''</summary>
        Friend Shared ReadOnly Property tipTrackBarMove() As String
            Get
                Return ResourceManager.GetString("tipTrackBarMove", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Année précédente.
        '''</summary>
        Friend Shared ReadOnly Property tipYearDown() As String
            Get
                Return ResourceManager.GetString("tipYearDown", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Année suivante.
        '''</summary>
        Friend Shared ReadOnly Property tipYearUp() As String
            Get
                Return ResourceManager.GetString("tipYearUp", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
